In [1]:
import pandas as pd

In [3]:
# 1. Create a DataFrame for the 201908-citibike-tripdata data. 

#File to load
citibike_data_to_load = "Resources/201908_citibike_tripdata.csv"

#Read the citibike data , and store it in a Pandas Dataframe.
citibike_data_df = pd.read_csv(citibike_data_to_load)

In [6]:
# 2. Check the datatypes of your columns. 
citibike_data_df.tail(10)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
2344214,532,2019-08-31 23:59:36.1200,2019-09-01 00:08:28.7850,3323.0,W 106 St & Central Park West,40.798186,-73.960591,3689.0,W 104 St & Amsterdam Ave,40.799041,-73.966495,33798,Subscriber,1989,2
2344215,838,2019-08-31 23:59:38.0510,2019-09-01 00:13:36.8530,3094.0,Graham Ave & Withers St,40.716981,-73.944859,3112.0,Milton St & Franklin St,40.729060,-73.957790,19826,Customer,1993,1
2344216,231,2019-08-31 23:59:39.0230,2019-09-01 00:03:30.4820,293.0,Lafayette St & E 8 St,40.730207,-73.991026,285.0,Broadway & E 14 St,40.734546,-73.990741,28225,Subscriber,1993,2
2344217,689,2019-08-31 23:59:41.4140,2019-09-01 00:11:10.8430,341.0,Stanton St & Mangin St,40.717821,-73.976289,439.0,E 4 St & 2 Ave,40.726281,-73.989780,32541,Subscriber,1988,2
2344218,1767,2019-08-31 23:59:45.7730,2019-09-01 00:29:13.6000,403.0,E 2 St & 2 Ave,40.725029,-73.990697,3141.0,1 Ave & E 68 St,40.765005,-73.958185,25832,Customer,1993,1
2344219,216,2019-08-31 23:59:46.2930,2019-09-01 00:03:23.0360,116.0,W 17 St & 8 Ave,40.741776,-74.001497,509.0,9 Ave & W 22 St,40.745497,-74.001971,38655,Subscriber,1972,1
2344220,117,2019-08-31 23:59:47.7970,2019-09-01 00:01:45.7440,3429.0,Hanson Pl & Ashland Pl,40.685068,-73.977908,353.0,S Portland Ave & Hanson Pl,40.685396,-73.974315,25264,Subscriber,1982,2
2344221,1614,2019-08-31 23:59:48.1560,2019-09-01 00:26:42.7760,387.0,Centre St & Chambers St,40.712733,-74.004607,3440.0,Fulton St & Adams St,40.692418,-73.989495,28485,Customer,1969,0
2344222,1301,2019-08-31 23:59:58.3620,2019-09-01 00:21:39.7040,3168.0,Central Park West & W 85 St,40.784727,-73.969617,423.0,W 54 St & 9 Ave,40.765849,-73.986905,38664,Customer,1969,0
2344223,419,2019-08-31 23:59:59.4520,2019-09-01 00:06:59.0210,447.0,8 Ave & W 52 St,40.763707,-73.985162,529.0,W 42 St & 8 Ave,40.757570,-73.990985,35210,Subscriber,1994,1

In [7]:
citibike_data_df.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id           float64
start station name          object
start station latitude     float64
start station longitude    float64
end station id             float64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
usertype                    object
birth year                   int64
gender                       int64
dtype: object

In [15]:
# 3. Convert the 'tripduration' column to datetime datatype.
citibike_data_df['tripduration'] = pd.to_datetime(citibike_data_df['tripduration'], unit='D')

In [16]:
# 4. Check the datatypes of your columns. 
citibike_data_df.dtypes

tripduration               datetime64[ns]
starttime                          object
stoptime                           object
start station id                  float64
start station name                 object
start station latitude            float64
start station longitude           float64
end station id                    float64
end station name                   object
end station latitude              float64
end station longitude             float64
bikeid                              int64
usertype                           object
birth year                          int64
gender                              int64
dtype: object

In [18]:
# 5. Export the Dataframe as a new CSV file without the index.
citibike_data_df.tail(10)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
2344214,1970-01-01 08:52:00,2019-08-31 23:59:36.1200,2019-09-01 00:08:28.7850,3323.0,W 106 St & Central Park West,40.798186,-73.960591,3689.0,W 104 St & Amsterdam Ave,40.799041,-73.966495,33798,Subscriber,1989,2
2344215,1970-01-01 13:58:00,2019-08-31 23:59:38.0510,2019-09-01 00:13:36.8530,3094.0,Graham Ave & Withers St,40.716981,-73.944859,3112.0,Milton St & Franklin St,40.729060,-73.957790,19826,Customer,1993,1
2344216,1970-01-01 03:51:00,2019-08-31 23:59:39.0230,2019-09-01 00:03:30.4820,293.0,Lafayette St & E 8 St,40.730207,-73.991026,285.0,Broadway & E 14 St,40.734546,-73.990741,28225,Subscriber,1993,2
2344217,1970-01-01 11:29:00,2019-08-31 23:59:41.4140,2019-09-01 00:11:10.8430,341.0,Stanton St & Mangin St,40.717821,-73.976289,439.0,E 4 St & 2 Ave,40.726281,-73.989780,32541,Subscriber,1988,2
2344218,1970-01-02 05:27:00,2019-08-31 23:59:45.7730,2019-09-01 00:29:13.6000,403.0,E 2 St & 2 Ave,40.725029,-73.990697,3141.0,1 Ave & E 68 St,40.765005,-73.958185,25832,Customer,1993,1
2344219,1970-01-01 03:36:00,2019-08-31 23:59:46.2930,2019-09-01 00:03:23.0360,116.0,W 17 St & 8 Ave,40.741776,-74.001497,509.0,9 Ave & W 22 St,40.745497,-74.001971,38655,Subscriber,1972,1
2344220,1970-01-01 01:57:00,2019-08-31 23:59:47.7970,2019-09-01 00:01:45.7440,3429.0,Hanson Pl & Ashland Pl,40.685068,-73.977908,353.0,S Portland Ave & Hanson Pl,40.685396,-73.974315,25264,Subscriber,1982,2
2344221,1970-01-02 02:54:00,2019-08-31 23:59:48.1560,2019-09-01 00:26:42.7760,387.0,Centre St & Chambers St,40.712733,-74.004607,3440.0,Fulton St & Adams St,40.692418,-73.989495,28485,Customer,1969,0
2344222,1970-01-01 21:41:00,2019-08-31 23:59:58.3620,2019-09-01 00:21:39.7040,3168.0,Central Park West & W 85 St,40.784727,-73.969617,423.0,W 54 St & 9 Ave,40.765849,-73.986905,38664,Customer,1969,0
2344223,1970-01-01 06:59:00,2019-08-31 23:59:59.4520,2019-09-01 00:06:59.0210,447.0,8 Ave & W 52 St,40.763707,-73.985162,529.0,W 42 St & 8 Ave,40.757570,-73.990985,35210,Subscriber,1994,1

In [20]:
citibike_data_df.to_csv(r'Resources/201908_citibike_tripdata_2.csv', index = False)